# Generated by Django 5.1.1 on 2024-09-24 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ヘッダ名')),
                ('profile_image_path', models.URLField(verbose_name='個人写真パス')),
                ('back_ground_image_path', models.URLField(verbose_name='背景写真パス')),
                ('is_active', models.BooleanField(default=False, verbose_name='有効フラグ')),
            ],
        ),
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='メニュー名')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='メニュー画像')),
            ],
        ),
        migrations.CreateModel(
            name='MyHistoryNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='歴史名称')),
            ],
        ),
        migrations.CreateModel(
            name='MyProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_text', models.TextField(max_length=2000, verbose_name='自己紹介文')),
            ],
        ),
        migrations.CreateModel(
            name='PositionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ポジション名')),
            ],
        ),
        migrations.CreateModel(
            name='SkillCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='スキルカテゴリ名')),
            ],
        ),
        migrations.CreateModel(
            name='SkillLevelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(verbose_name='スキルレベル')),
            ],
        ),
        migrations.CreateModel(
            name='SkillNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='スキル名')),
                ('description_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='詳細説明1')),
                ('description_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='詳細説明2')),
                ('description_3', models.CharField(blank=True, max_length=100, null=True, verbose_name='詳細説明3')),
                ('description_4', models.CharField(blank=True, max_length=100, null=True, verbose_name='詳細説明4')),
                ('description_5', models.CharField(blank=True, max_length=100, null=True, verbose_name='詳細説明5')),
            ],
        ),
        migrations.CreateModel(
            name='SkillPeriodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='スキル使用期間')),
            ],
        ),
        migrations.CreateModel(
            name='MyHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='詳細内容')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_profile.myhistorynamemodel', verbose_name='歴史名称')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='プロジェクト名')),
                ('overview', models.TextField(max_length=1000, verbose_name='概要')),
                ('back_ground', models.TextField(max_length=1000, verbose_name='背景')),
                ('period_from', models.DateField(blank=True, null=True, verbose_name='期間開始')),
                ('period_to', models.DateField(blank=True, null=True, verbose_name='期間終了')),
                ('scale', models.CharField(max_length=100, verbose_name='規模')),
                ('descriptions1', models.CharField(blank=True, max_length=100, null=True, verbose_name='詳細業務内容1')),
                ('descriptions2', models.CharField(blank=True, max_length=100, null=True, verbose_name='詳細業務内容2')),
                ('descriptions3', models.CharField(blank=True, max_length=100, null=True, verbose_name='詳細業務内容3')),
                ('descriptions4', models.CharField(blank=True, max_length=100, null=True, verbose_name='詳細業務内容4')),
                ('descriptions5', models.CharField(blank=True, max_length=100, null=True, verbose_name='詳細業務内容5')),
                ('descriptions6', models.CharField(blank=True, max_length=100, null=True, verbose_name='詳細業務内容6')),
                ('descriptions7', models.CharField(blank=True, max_length=100, null=True, verbose_name='詳細業務内容7')),
                ('descriptions8', models.CharField(blank=True, max_length=100, null=True, verbose_name='詳細業務内容8')),
                ('descriptions9', models.CharField(blank=True, max_length=100, null=True, verbose_name='詳細業務内容9')),
                ('descriptions10', models.CharField(blank=True, max_length=100, null=True, verbose_name='詳細業務内容10')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_profile.positionmodel', verbose_name='ポジション名')),
                ('skill_names', models.ManyToManyField(related_name='projects_skill_name', to='my_profile.skillnamemodel', verbose_name='スキル名')),
            ],
        ),
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='ロゴ画像パス')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_profile.skillcategorymodel', verbose_name='スキルカテゴリ名')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_profile.skilllevelmodel', verbose_name='スキルレベル')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_profile.skillnamemodel', verbose_name='スキル名')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_profile.skillperiodmodel', verbose_name='スキル使用期間')),
            ],
        ),
    ]
