# Generated by Django 5.1.1 on 2024-09-22 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyHistoryNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='歴史名称')),
            ],
        ),
        migrations.CreateModel(
            name='MyHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decriotion', models.CharField(max_length=100, verbose_name='詳細内容')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_profile.myhistorynamemodel', verbose_name='歴史名称')),
            ],
        ),
    ]
