# Generated by Django 5.1.1 on 2024-09-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofilemodel',
            name='profile_text',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='自己紹介文'),
        ),
    ]
