# Generated by Django 5.1.1 on 2024-09-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0002_alter_myprofilemodel_profile_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='icons/', verbose_name='メニューアイコン'),
        ),
    ]
