# Generated by Django 5.1.1 on 2024-09-22 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0002_myhistorynamemodel_myhistorymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myhistorymodel',
            old_name='decriotion',
            new_name='description',
        ),
    ]
