# Generated by Django 5.1.1 on 2024-09-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0003_rename_decriotion_myhistorymodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillmodel',
            name='image_path',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='ロゴ画像パス'),
        ),
    ]
