# Generated by Django 5.1.1 on 2024-09-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0004_skillmodel_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='メニュー名')),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='メニュー画像')),
            ],
        ),
    ]
